from . import helpdesk_mixin
from . import sla_mixin
from . import ir_websocket
from . import helpdesk_ticket_category
from . import helpdesk_ticket_tag
from . import helpdesk_ticket
from . import helpdesk_ticket_comment
from . import helpdesk_ticket_close_wizard
from . import helpdesk_ticket_bulk_assign_wizard
from . import res_partner
