{
    'name': 'Messagerie — Boîte email unifiée',
    'version': '19.0.2.0.0',
    'category': 'Productivity/Discuss',
    'summary': "Réception IMAP centralisée, réponse, brouillons et tri sans quitter Odoo",
    'author': 'ADICOPS',
    'license': 'LGPL-3',
    'depends': ['mail'],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'data/ir_cron.xml',
        'views/oski_mail_inbox_views.xml',
        'views/oski_mailbox_views.xml',
        'views/oski_mail_imap_action_views.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'application': True,
}
